import{i as c,S as h}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const m="46950452-7815ceb93240c1d1876de68f7",g="https://pixabay.com/api/";function y(n){const r=new URLSearchParams({key:m,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}),s=`${g}?${r.toString()}`;return fetch(s).then(t=>{if(!t.ok)throw new Error("Oooooppppssss");return t.json()}).then(t=>(console.log(t),t.hits.length===0?(c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red"}),[]):t.hits)).catch(t=>{console.log(t),c.error({title:"Error",message:"",position:"topRight",backgroundColor:"red"})})}const l=document.querySelector(".list");function b(n){const r=n.map(({webformatURL:s,largeImageURL:t,tags:e,likes:o,views:i,comments:f,downloads:d})=>`
        <div class="gallery-item">
            <a href="${t}">
                <img src="${s}" alt="${e}" width="360" height="200"/>
            </a>
            <div class="info">
                <p class="info-text"><b class="text2">Likes:</b> ${o}</p>
                <p class="info-text"><b class="tex2">Views:</b> ${i}</p>
                <p class="info-text"><b class="text2">Comments:</b> ${f}</p>
                <p class="info-text"><b class="text2">Downloads:</b> ${d}</p>
            </div>
        </div>
    `).join("");l.innerHTML="",l.insertAdjacentHTML("beforeend",r)}const u=document.querySelector(".search-form"),L=document.querySelector(".search-form input"),p=document.querySelector(".loader");let a;u.addEventListener("submit",x);function x(n){n.preventDefault(),console.log("Працює чи нє");const r=L.value.trim();if(console.log(r),r==="")return c.info({title:"Error",message:"Please enter a search query.",position:"topRight",backgroundColor:"red"});S(),y(r).then(s=>{s&&s.length>0&&(b(s),a?a.refresh():a=new h(".gallery-item a",{captionsData:"alt",captionDelay:250}))}).catch(s=>{console.log(s),c.error({title:"Error",message:"Error",position:"topRight",backgroundColor:"red"})}).finally(()=>{E(),u.reset()})}function S(){p.style.display="block"}function E(){p.style.display="none"}
//# sourceMappingURL=index.js.map
